spring:
  freemarker:
    template-loader-path: classpath:/templates/
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.227.133:3306/sqlfather
    username: root
    password: admin
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''